### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by fangpinsern** [kisp-nus/cs3235-cert-chain#1]
Doesnt work on python 3.6
